version: '3'
services:
  chrome_standalone:
    restart: always
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - ${WEBDRIVER_PORT}:4444
      - "5900"
    stdin_open: true
