version: '3'
services:
  chrome_standalone:
    restart: always
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
    ports:
      - 4444:4444
      - "5900"
    stdin_open: true
